coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 1%  
    patch:
      default:
        target: 50%
        threshold: 1%
        informational: true
  ignore:
    - "arbiter-core/contracts/*"
    - "arbiter/arbiter-core/benches*"
    - "arbiter/arbiter-core/src/bindings"
    - "arbiter/arbiter-bindings/*"
    
