output_path = "output/"
output_filename = "test.json"
provider = "https://eth.llamarpc.com"
block_number = 18228556

# WE SHOULD STORE THESE IN A MAP ACTUALLy
[contracts.weth]
address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" 
artifacts_path = "bin/tests/WETH.sol/WETH.json"

[contracts.weth.mappings]
balanceOf = [
  "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045", # vitalik.eth as of 10/2/2023
]