[package]
name = "arbiter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tokio = { version = "1.17.0", features = ["macros", "full"] }
clap = { version = "4.0.32", features = ["derive"] }
serde = { version = "1.0.152", features =["derive"] }
clairvoyance = { path = "../clairvoyance" }
utils = { path = "../utils" }
thiserror = "1.0.38"
ethers = "1.0.0"
eyre = "0.6.6"
toml = "0.5.10"
revm = "2.3.1"
revm_precompiles = "1.1.2"
bytes = "1.3.0"
anyhow = "1.0.68"
hex = { version = "0.4", default-features = false }

tokio = { version = "1.23", features = [
    "rt-multi-thread",
    "macros",
]}
ethers-providers = "1.0.2"
ethers-core = "1.0.2"
futures = "0.3.24"

# revm-interpreter = { path = "../interpreter", default-features = false }


