[package]
name = "arbiter-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers.workspace = true
revm.workspace = true
revm-primitives.workspace = true
serde.workspace = true
