[package]
name = "simulate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.25"
revm = "2.3.1"
tokio = { version = "1.24.2", features = ["macros", "full"] }
ethers = "1.0.0"
bytes = "1.3.0"
hex = { version = "0.4", default-features = false }