[package]
name = "simulate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# execution
revm = "3.0.0"

# async
tokio = { version = "1.23", features = [
    "macros",
    "full"
]}
futures = "0.3.28"
tokio-stream = "0.1.12" # May not be needed
crossbeam-channel = "0.5.7"
async-trait = "0.1.68"

# price_simulation
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
plotly = "0.8.3"

bytes = "1.4.0"


# added for tests
bindings = { path = "../bindings" }
ethers = "=2.0.0"
hex = { version = "0.4", default-features = false }