[sim]
number_of_price_paths = 100
number_of_volatilities = 100
timestep = 0.0027397
timescale = "years"
num_steps = 365
initial_price = 1
seed = 887

[gbm]
drift = 0.1
volatility = 0.07

[ou]
ou_mean_reversion_speed = 50
ou_mean = 1

[chain]
contract = "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
rpc_url = "https://eth-mainnet.g.alchemy.com/v2/I93POQk49QE9O-NuOz7nj7sbiluW76it"