name: Bump patch version

on:
  pull_request:
    types:
      - closed

jobs:
  bump_version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Configure Git
        run: |
          git config --global user.email "waylonjepsen1@gmail.com"
          git config --global user.name "Waylon Jepsen"

      - name: Bump patch version
        run: |
          find . -name 'Cargo.toml' -execdir sh -c '
            cargo bump patch
            VERSION=$(cargo metadata --format-version 1 | jq -r ".packages[] | select(.manifest_path == \"$(pwd)/Cargo.toml\") | .version")
            git add Cargo.toml
            git commit -m "Bump version in $(dirname $(pwd)) to $VERSION" ' \;
          git push
