on: [push]

name: Rust

jobs:
  tests-stable:
    name: Tests (Stable)
    runs-on: ubuntu-latest
    env:
      ETH_RPC_URL: https://eth-mainnet.alchemyapi.io/v2/Lc7oIGYeL_QvInzI0Wiu_pOZZDEKBrdf
      CODECOV_TOKEN: ${CODECOV_TOKEN}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: cargo test
        run: |
          cargo test --all --all-features --exclude bindings
          bash <(curl -s https://codecov.io/bash)

      - name: Run coverage using rust-grcov
        uses: actions-rs/grcov@v0.1.5

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          env: ${{ secrets.CODECOV_TOKEN }}
        # run:
        # run: |
        #   curl -Os https://uploader.codecov.io/latest/linux/codecov
        #   chmod +x codecov
        #   ./codecov -t ${CODECOV_TOKEN}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt, clippy
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy -- -A clippy::module_inception

  # coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Upload coverage reports to Codecov
  #       uses: codecov/codecov-action@v3
